Repository HackSC/hibiscus, pull requests merged in 2023-01, with the labels that each got.

#296 hib 89 hib 108
  apps/dashboard/common/constants.ts
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/components/hackerform/common-styled-components.tsx
  apps/dashboard/components/hackerform/file-question/file-question.tsx
  apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx
  apps/dashboard/components/hackerform/hackform/hackform.tsx
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
  apps/dashboard/hooks/use-hackform/use-hackform.ts
  apps/dashboard/layouts/portal-layout.tsx
  apps/dashboard/pages/_app.tsx
  apps/dashboard/pages/apply-2023/index.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/pages/styles.css
  apps/dashboard/store/hackform-slice.ts
  libs/ui-kit-2023/src/lib/arrow-button/arrow-button.tsx
  package.json
  yarn.lock
Labels: automerge

#295 Dashboard SSO integration
  .env.example
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/components/top-bar/top-bar.tsx
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/layouts/portal-layout.tsx
  apps/dashboard/middleware.ts
  apps/dashboard/pages/api/callback.ts
  apps/dashboard/pages/index.tsx
  apps/dashboard/project.json
  apps/sso/components/signup-card/signup-card.tsx
  apps/sso/components/verify-card/verify-card.tsx
  libs/env/src/index.ts
  libs/hibiscus-supabase-client/src/index.ts
  libs/sso-client/src/lib/sso-client.ts
  libs/types/src/lib/roles.ts
  supabase/config.toml
  supabase/migrations/20230109020457_add_email_and_profile_rls.sql
Labels: automerge, db-migration

#298 Reduce supabase database queries on dashboard
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/layouts/portal-layout.tsx
  apps/dashboard/pages/index.tsx
  libs/env/src/index.ts
Labels: automerge

#299 Fix blocked schools endpoint on dashboard
  apps/dashboard/middleware.ts
  apps/dashboard/pages/404/index.tsx
  apps/dashboard/pages/apply-2023/index.tsx
Labels: automerge

#301 Fix database migrations
  libs/hibiscus-supabase-client/src/index.ts
  supabase/migrations/20230109020457_add_email_and_profile_rls.sql
Labels: automerge, db-migration

#302 improved security for Hackform API calls
  apps/dashboard/common/api.ts
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/common/types.ts
  apps/dashboard/components/hackerform/file-question/file-question.tsx
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/layouts/portal-layout.tsx
  apps/dashboard/middleware.ts
  apps/dashboard/pages/404/index.tsx
  apps/dashboard/pages/_app.tsx
  apps/dashboard/pages/api/hackform.ts
  apps/dashboard/pages/apply-2023/index.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/store/menu-slice.ts
  libs/hackform-client/src/lib/data-client.ts
  libs/hibiscus-supabase-client/src/index.ts
  libs/types/src/lib/index.ts
  libs/types/src/lib/supabase.gen.ts
  libs/types/src/lib/user.ts
  package.json
  supabase/migrations/20230110032809_linking_app_id.sql
Labels: automerge, db-migration

#306 simple Pointr implementation
  .husky/pre-commit
  apps/pointr/.eslintrc.json
  apps/pointr/common/link.repository.ts
  apps/pointr/index.d.ts
  apps/pointr/jest.config.ts
  apps/pointr/next-env.d.ts
  apps/pointr/next.config.js
  apps/pointr/pages/[shortlink]/index.tsx
  apps/pointr/pages/_app.tsx
  apps/pointr/pages/_document.tsx
  apps/pointr/pages/index.tsx
  apps/pointr/pages/styles.css
  apps/pointr/project.json
  apps/pointr/public/.gitkeep
  apps/pointr/specs/index.spec.tsx
  apps/pointr/tsconfig.json
  apps/pointr/tsconfig.spec.json
  libs/types/src/lib/supabase.gen.ts
  supabase/migrations/20230111213858_create_pointr_table.sql
  workspace.json
Labels: automerge, db-migration

#308 setup event service + migrations
  .env.example
  apps/event-service/.gitignore
  apps/event-service/app.py
  apps/event-service/requirements.txt
  supabase/migrations/20230116021513_events_pinned_tables.sql
Labels: db-migration

#311 create db migration – discord id bot
  supabase/migrations/20230116101513_discord-id-bot-migration.sql
Labels: automerge, db-migration

#310 Hib 90 application status on portal
  apps/dashboard/components/hacker-portal/hacker-portal.stories.tsx
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hackerform/hackform/hackform.tsx
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/pages/index.tsx
  libs/styles/src/lib/colors.ts
  libs/types/src/lib/application-status.ts
  libs/types/src/lib/supabase.gen.ts
  libs/types/src/lib/user.ts
  supabase/migrations/20230116062208_application_status.sql
Labels: automerge, db-migration

#309 SSO Guard API paths
  apps/dashboard/middleware.ts
  apps/sso/middleware.ts
  apps/sso/pages/api/unauthorized.ts
  libs/sso-client/src/lib/sso-client.ts
Labels: automerge

#313 add airplane scripts; `setOptions` for HBSC
  .gitignore
  .kodiak.toml
  .prettierignore
  apps/airplane/airplane.yaml
  apps/airplane/project.json
  apps/airplane/tasks/get_2023_hackers.py
  apps/airplane/tasks/get_2023_hackers.task.yaml
  apps/airplane/tasks/requirements.txt
  apps/airplane/tsconfig.json
  apps/event-service/project.json
  apps/event-service/requirements.txt
  libs/env/src/index.ts
  libs/hackform-client/src/lib/data-client.ts
  libs/hibiscus-supabase-client/src/index.ts
  package.json
  workspace.json
  yarn.lock
Labels: automerge

#314 hackform responsiveness
  apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx
  apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx
  apps/dashboard/components/hackerform/long-text-question/long-text-question.tsx
  apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx
  apps/dashboard/components/hackerform/other-field.tsx
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
  apps/dashboard/components/hackerform/single-choice-input/single-choice-input.tsx
  apps/dashboard/pages/index.tsx
  libs/ui-kit-2023/src/lib/date-picker/date-picker.tsx
  libs/ui-kit-2023/src/lib/searchable-option-select-input/searchable-option-select-input.tsx
Labels: automerge

#315 file upload improvements
  apps/dashboard/components/hackerform/file-question/file-question.tsx
  apps/dashboard/store/hackform-slice.ts
Labels: automerge

#316 Replace resend confirmation email link with message
  apps/sso/components/verify-card/verify-card.tsx
Labels: automerge

#317 Hib 126 polish sso
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/pages/index.tsx
  apps/sso/components/login-card/login-card.tsx
  apps/sso/components/otp-input/otp-input.spec.tsx
  apps/sso/components/otp-input/otp-input.tsx
  apps/sso/components/reset-card/reset-card.tsx
  apps/sso/components/reset-card/reset-email-card.tsx
  apps/sso/components/signup-card/signup-card.tsx
  apps/sso/components/verify-card/verify-card.tsx
  package.json
  yarn.lock
Labels: automerge

#319 redirect hack.sc to hacksc.com
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/pointr/pages/index.tsx
  apps/sso/components/verify-card/verify-card.tsx
  libs/types/src/lib/supabase.gen.ts
Labels: automerge

#321 fix application status logic
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
  apps/sso/components/login-card/login-card.tsx
  apps/sso/components/signup-card/signup-card.tsx
  apps/sso/components/verify-card/verify-card.tsx
Labels: automerge

#320 Apply redirect to signup
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/middleware.ts
  apps/sso/pages/signup/index.tsx
  libs/env/src/index.ts
  libs/sso-client/src/lib/sso-client.ts
Labels: automerge

#300 Hib 82 create team service frontend
  .env.example
  apps/dashboard/common/api.ts
  apps/dashboard/common/types.ts
  apps/dashboard/components/gray-box/gray-box.tsx
  apps/dashboard/components/gray-content-box/gray-content-box.tsx
  apps/dashboard/components/hackerform/hackform-question-header/hackform-question-header.tsx
  apps/dashboard/components/red-span.tsx
  apps/dashboard/components/team/no-team-placeholder.tsx
  apps/dashboard/components/team/team-create-form.tsx
  apps/dashboard/components/team/team-header.tsx
  apps/dashboard/components/team/team-members-widget.tsx
  apps/dashboard/components/team/team.module.css
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/hooks/use-team/use-team.tsx
  apps/dashboard/pages/_app.tsx
  apps/dashboard/pages/api/invite/accept.ts
  apps/dashboard/pages/api/invite/reject.ts
  apps/dashboard/pages/api/organizer/create.ts
  apps/dashboard/pages/api/organizer/disband.ts
  apps/dashboard/pages/api/organizer/invite.ts
  apps/dashboard/pages/api/organizer/kick.ts
  apps/dashboard/pages/api/resume.ts
  apps/dashboard/pages/api/team.ts
  apps/dashboard/pages/apply-2023/index.tsx
  apps/dashboard/pages/team/index.tsx
  apps/dashboard/pages/team/invite/accept.tsx
  apps/dashboard/pages/team/invite/reject.tsx
  apps/dashboard/repository/dashboard.repository.ts
  apps/dashboard/repository/invite.repository.ts
  apps/dashboard/repository/user.repository.ts
  libs/hibiscus-supabase-client/src/index.ts
  libs/types/src/lib/supabase.gen.ts
  libs/types/src/lib/user.ts
  libs/ui-kit-2023/src/lib/button/button.tsx
  libs/ui/src/index.ts
  libs/ui/src/lib/modal/modal.module.css
  libs/ui/src/lib/modal/modal.tsx
  package.json
  supabase/migrations/20221226001211_create_teams_tables.sql
  supabase/migrations/20230103024544_fix_team_invite_schema.sql
  supabase/seed.sql
  yarn.lock
Labels: automerge, db-migration

#323 add application status fill
  supabase/migrations/20230119083157_add_application_statuses.sql
Labels: automerge, db-migration

#325 defer team service
  apps/dashboard/store/menu-slice.ts
Labels: automerge

#322 add illustrations to hackform
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
  apps/dashboard/public/hackform-illustrations/detective-astronaut.svg
  apps/dashboard/public/hackform-illustrations/detective-curious.svg
  apps/dashboard/public/hackform-illustrations/detective-dance.svg
  apps/dashboard/public/hackform-illustrations/detective-lying.svg
  apps/dashboard/public/hackform-illustrations/detective.svg
  apps/dashboard/public/hackform-illustrations/earth-dancing.svg
  apps/dashboard/public/hackform-illustrations/earth-standing.svg
  apps/dashboard/public/hackform-illustrations/earth-waving.svg
  apps/dashboard/public/hackform-illustrations/earth.svg
  apps/dashboard/public/hackform-illustrations/green-puzzle.svg
  apps/dashboard/public/hackform-illustrations/heart-astronaut.svg
  apps/dashboard/public/hackform-illustrations/heart-flying.svg
  apps/dashboard/public/hackform-illustrations/heart-standing.svg
  apps/dashboard/public/hackform-illustrations/heart.svg
  apps/dashboard/public/hackform-illustrations/postcard-plane.svg
  apps/dashboard/public/hackform-illustrations/postcard-traveler.svg
  apps/dashboard/public/hackform-illustrations/postcard-world.svg
  apps/dashboard/public/hackform-illustrations/postcard.svg
  apps/dashboard/public/hackform-illustrations/purple-planet-jump.svg
  apps/dashboard/public/hackform-illustrations/purple-planet-stand.svg
  apps/dashboard/public/hackform-illustrations/purple-planet.svg
  apps/dashboard/public/hackform-illustrations/purple-puzzle.svg
  apps/dashboard/public/hackform-illustrations/puzzle.svg
  apps/dashboard/public/hackform-illustrations/stacking-puzzle.svg
  apps/dashboard/public/hackform-illustrations/stamp-coin.svg
  apps/dashboard/public/hackform-illustrations/stamp-earth.svg
  apps/dashboard/public/hackform-illustrations/stamp-hacksc.svg
  apps/dashboard/public/hackform-illustrations/stamp-heart.svg
  apps/dashboard/public/hackform-illustrations/stamp-planet.svg
  apps/dashboard/public/hackform-illustrations/stamp-puzzle.svg
Labels: automerge

#328 Suhit/www 2023
  apps/www-2023/common/sendgrid.client.ts
  apps/www-2023/components/apply-now/apply-now.spec.tsx
  apps/www-2023/components/apply-now/apply-now.tsx
  apps/www-2023/components/email-newsletter-input-section/email-newsletter-input-section.spec.tsx
  apps/www-2023/components/email-newsletter-input-section/email-newsletter-input-section.tsx
  apps/www-2023/components/faqs/faqs.tsx
  apps/www-2023/components/footer/footer.tsx
  apps/www-2023/components/hero/hero.tsx
  apps/www-2023/components/navbar/desktop-navbar/desktop-navbar.tsx
  apps/www-2023/components/navbar/mobile-navbar/mobile-navbar.tsx
  apps/www-2023/components/newsletter/newsletter.spec.tsx
  apps/www-2023/components/newsletter/newsletter.tsx
  apps/www-2023/components/solution-challenge/solution-challenge.tsx
  apps/www-2023/components/speakers/speakers.tsx
  apps/www-2023/components/sponsors/sponsors.spec.tsx
  apps/www-2023/components/sponsors/sponsors.tsx
  apps/www-2023/components/verticals/verticals.tsx
  apps/www-2023/contexts/SendgridClientProvider.tsx
  apps/www-2023/hooks/use-sendgrid-client/use-sendgrid-client.tsx
  apps/www-2023/pages/_app.tsx
  apps/www-2023/pages/index.tsx
  apps/www-2023/public/img/favicon.ico
  apps/www-2023/public/img/graphics/bg-desktop.svg
  apps/www-2023/public/img/graphics/bg-mobile.svg
  apps/www-2023/public/img/graphics/hacksc.riv
  apps/www-2023/public/img/graphics/heart.svg
  apps/www-2023/public/img/graphics/puzzle.svg
  apps/www-2023/public/img/logos/accessibility.svg
  apps/www-2023/public/img/logos/carc.png
  apps/www-2023/public/img/logos/elastic.png
  apps/www-2023/public/img/logos/facebook.svg
  apps/www-2023/public/img/logos/instagram.svg
  apps/www-2023/public/img/logos/linkedin.svg
  apps/www-2023/public/img/logos/logo.svg
  apps/www-2023/public/img/logos/mail.svg
  apps/www-2023/public/img/logos/twitter.svg
  apps/www-2023/public/img/logos/vercel.svg
  apps/www-2023/public/img/speakers/mark.png
  apps/www-2023/public/img/speakers/matt.png
  apps/www-2023/public/img/speakers/michael.png
  package.json
  workspace.json
  yarn.lock
Labels: automerge

#329 Database migrations for events
  supabase/migrations/20230116025536_add_wristband_id.sql
  supabase/migrations/20230116025537_add_volunteer_access.sql
  supabase/migrations/20230119174552_add_leaderboard_table.sql
  supabase/migrations/20230119180516_add_event_log_table.sql
  supabase/migrations/20230119181530_add_bonus_points_tables.sql
  supabase/migrations/20230119182613_add_access_policies.sql
  supabase/migrations/20230119191100_add_bonus_point_statuses.sql
  supabase/seed.sql
Labels: automerge, db-migration

#332 add illustrations to team-service
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
  apps/dashboard/pages/team/index.tsx
Labels: automerge

#331 add amplify.yml
  amplify.yml
Labels: automerge

#334 www 2023 fixes
  apps/www-2023/components/apply-now/apply-now.tsx
  apps/www-2023/components/hero/hero.tsx
  apps/www-2023/components/newsletter/newsletter.tsx
  apps/www-2023/public/img/graphics/hacksc.riv
  package.json
  yarn.lock
Labels: automerge

#335 quick fix for ux
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
Labels: automerge

#336 fixed newsletter responsiveness
  apps/www-2023/components/hero/hero.tsx
  apps/www-2023/components/newsletter/newsletter.tsx
  apps/www-2023/public/img/graphics/bg-mobile.svg
Labels: automerge

#337 2023 design update
  apps/sso/components/gray-link/gray-link.tsx
  apps/sso/components/login-card/login-card.tsx
  apps/sso/components/otp-input/otp-input.tsx
  apps/sso/components/signup-card/signup-card.tsx
  apps/sso/components/verify-card/verify-card.tsx
  apps/sso/pages/_app.tsx
  apps/sso/pages/login/index.tsx
  apps/sso/pages/signup/index.tsx
  apps/sso/pages/verify/index.tsx
  apps/sso/public/static/images/logo-2023.svg
  libs/ui-kit-2023/src/lib/one-line-text/one-line-text.tsx
Labels: automerge

#342 Fix token refresh (closes HIB-138)
  apps/sso/components/login-guard.tsx
  apps/sso/components/verify-card/verify-card.tsx
  libs/hibiscus-supabase-client/src/index.ts
  libs/types/src/lib/api/sso.ts
Labels: automerge

#343 fix speaker bio
  apps/www-2023/components/speakers/speakers.tsx
Labels: automerge

#340 fix not showing user application status after app submit
  .env.example
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
  libs/env/src/index.ts
  libs/hackform-client/src/lib/data-client.ts
Labels: automerge

#341 Hib 136 implement sponsor portal
  amplify.yml
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
  apps/dashboard/components/sponsor-portal/hacker-profile.stories.tsx
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/hacker-tab.stories.tsx
  apps/dashboard/components/sponsor-portal/hacker-tab.tsx
  apps/dashboard/components/sponsor-portal/sponsor-portal.stories.tsx
  apps/dashboard/components/sponsor-portal/sponsor-portal.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/pages/sponsor-booth/index.tsx
  apps/dashboard/pages/team/index.tsx
  apps/dashboard/public/arrow.svg
  apps/dashboard/public/download-button.svg
  apps/dashboard/public/note.svg
  apps/dashboard/public/save.svg
  apps/dashboard/public/x-button.svg
  apps/www-2023/components/apply-now/apply-now.tsx
  apps/www-2023/components/hero/hero.tsx
  apps/www-2023/components/newsletter/newsletter.tsx
  apps/www-2023/public/img/graphics/hacksc.riv
  libs/types/src/lib/index.ts
  package.json
  yarn.lock
Labels: automerge

#347 add sponsor logo
  apps/www-2023/components/sponsors/sponsors.tsx
  apps/www-2023/public/img/logos/sticker-mule-logo-white.png
Labels: automerge

#345 fix hackform responsiveness
  apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx
  apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx
  apps/dashboard/components/hackerform/long-text-question/long-text-question.tsx
  apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx
  apps/dashboard/components/hackerform/other-field.tsx
  apps/dashboard/components/hackerform/question-creator/question-creator.tsx
Labels: automerge

#360 reduce word count
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/pages/api/resume.ts
Labels: automerge

#356 Fix Dashboard port number
  apps/dashboard/project.json
Labels: automerge

#361 Make changes for merge request.
  supabase/migrations/20230125064704_add_notes_and_edit_participants.sql
Labels: automerge, db-migration

#364 typo
  apps/www-2023/components/faqs/faqs.tsx
Labels: automerge

#365 add mock sponsor api
  apps/dashboard/common/mock-sponsor.ts
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/hacker-tab.tsx
  apps/dashboard/pages/sponsor-booth/index.tsx
  apps/dashboard/store/menu-slice.ts
  package.json
  yarn.lock
Labels: automerge

#358 Add api to get events by day
  apps/event-service/app.py
Labels: automerge

#350 Disabled button
  libs/ui-kit-2023/src/lib/button/button.tsx
Labels: automerge

#367 Add option to disable SSO integration in dev environments
  .env.example
  libs/env/src/index.ts
  libs/sso-client/src/lib/sso-client.ts
Labels: automerge

#371 Add script to create fake user
  tools/scripts/create-fake-user.ts
Labels: automerge

#369 Change MAX_AGE env variable to 1 week
  libs/sso-client/src/lib/sso-client.ts
Labels: automerge

#376 add sentry to dashboard
  .github/workflows/ci.yml
  .gitignore
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
  apps/dashboard/next.config.js
  apps/dashboard/project.json
  apps/dashboard/sentry.client.config.ts
  apps/dashboard/sentry.edge.config.ts
  apps/dashboard/sentry.properties
  apps/dashboard/sentry.server.config.ts
  package.json
  yarn.lock
Labels: automerge

#378 change codeowners
  CODEOWNERS
Labels: automerge

#375 Hib 144 create rsvp form
  apps/dashboard/common/api.ts
  apps/dashboard/common/constants.ts
  apps/dashboard/common/hackform.metadata.tsx
  apps/dashboard/common/utils.ts
  apps/dashboard/components/battlepass/coming-soon-battlepass-placeholder.tsx
  apps/dashboard/components/gray-box/gray-box.tsx
  apps/dashboard/components/hacker-portal/coming-soon.tsx
  apps/dashboard/components/hacker-portal/congrats-message.tsx
  apps/dashboard/components/hacker-portal/declined-placeholder.tsx
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
  apps/dashboard/components/hackerform/searchable-options-question/searchable-options-question.tsx
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/components/rsvp-form/rsvp-form.tsx
  apps/dashboard/components/team/team-create-form.tsx
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts
  apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.tsx
  apps/dashboard/layouts/portal-layout.tsx
  apps/dashboard/pages/_app.tsx
  apps/dashboard/pages/api/resume.ts
  apps/dashboard/pages/apply-2023/index.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/sentry.client.config.ts
  apps/dashboard/sentry.edge.config.ts
  apps/dashboard/sentry.server.config.ts
  libs/env/src/index.ts
  libs/types/src/lib/index.ts
  libs/types/src/lib/supabase.gen.ts
  libs/types/src/lib/user.ts
  libs/ui-kit-2023/src/index.ts
  libs/ui-kit-2023/src/lib/button/button.tsx
  libs/ui-kit-2023/src/lib/combobox/combobox.stories.tsx
  libs/ui-kit-2023/src/lib/combobox/combobox.tsx
  libs/ui-kit-2023/src/lib/one-line-text/one-line-text.tsx
  libs/ui/src/lib/link/link.tsx
  supabase/migrations/20230126033646_rsvp_form_modifications.sql
Labels: automerge, db-migration

#382 screen aspect ratio fix
  apps/www-2023/components/hero/hero.tsx
Labels: automerge

#383 apps closed logic on dashboard + hackform; rejection message
  apps/dashboard/components/hacker-portal/apps-closed-placeholder.tsx
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hacker-portal/rejection-message.tsx
  apps/dashboard/pages/apply-2023/index.tsx
  apps/dashboard/pages/index.tsx
  package.json
  yarn.lock
Labels: automerge

#384 applications closed
  apps/www-2023/components/apply-now/apply-now.tsx
Labels: automerge

#380 Hib 149 implement additional sponsor portal features
  apps/dashboard/common/api.ts
  apps/dashboard/common/mock-sponsor.ts
  apps/dashboard/components/sponsor-portal/dropdown.stories.tsx
  apps/dashboard/components/sponsor-portal/dropdown.tsx
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/hacker-tab.tsx
  apps/dashboard/pages/api/companies.ts
  apps/dashboard/pages/api/company/[companyId].ts
  apps/dashboard/pages/participant-database/index.tsx
  apps/dashboard/pages/sponsor-booth/index.tsx
  apps/dashboard/public/dropdown-arrow.svg
  apps/dashboard/public/x-button.svg
  apps/dashboard/repository/dashboard.repository.ts
  supabase/migrations/20230126014013_add_target_majors_and_grads.sql
Labels: automerge
