Repository HackSC/hibiscus, pull requests merged in 2023-02, with the labels that each got.

#386 reset password hidden
  apps/sso/components/reset-card/reset-card.tsx
Labels: automerge

#387 enhancements for RSVP stuff
  apps/dashboard/components/hacker-portal/apps-closed-placeholder.tsx
  apps/dashboard/components/hacker-portal/congrats-message.tsx
  apps/dashboard/components/hacker-portal/rejection-message.tsx
  apps/dashboard/components/rsvp-form/rsvp-form.tsx
  libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx
Labels: automerge

#388 Fix reset email double confirmation bug
  apps/sso/components/reset-card/reset-card.tsx
  supabase/config.toml
Labels: automerge

#389 port feature flags to redis + rsvp form open ff
  .env.example
  apps/dashboard/components/battlepass/battlepass-description.tsx
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/components/hacker-portal/rsvp-closed-placeholder.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/repository/feature-flag.repository.ts
  libs/env/src/index.ts
  libs/hibiscus-supabase-client/src/index.ts
  package.json
  yarn.lock
Labels: automerge

#390 Vincent/attendee sponsor apis
  apps/dashboard/pages/api/sponsor/attendees.ts
  apps/dashboard/repository/__tests__/company.repository.test.ts
  apps/dashboard/repository/attendee.repository.ts
  apps/dashboard/repository/company.repository.ts
  apps/dashboard/repository/dashboard.repository.ts
  libs/types/src/lib/supabase.gen.ts
  supabase/migrations/20230130024217_add_table_company_saved_user_profiles.sql
  supabase/migrations/20230201213837_change_event_log_fkey.sql
Labels: automerge

#391 Vincent/attendee sponsor apis
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
Labels: automerge

#392 Vincent/attendee sponsor apis
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/pages/api/sponsor/attendees.ts
  apps/dashboard/repository/attendee.repository.ts
Labels: automerge

#395 speaker added - neil davé
  apps/www-2023/components/speakers/speakers.tsx
  apps/www-2023/public/img/speakers/neil.png
Labels: automerge

#394 Add implementation for notes api.
  apps/dashboard/pages/api/notes.ts
  apps/dashboard/repository/notes.repository.ts
Labels: automerge

#396 use mongodb instead for feature flags
  .env.example
  apps/dashboard/repository/feature-flag.repository.ts
  libs/env/src/index.ts
  package.json
  yarn.lock
Labels: automerge

#397 Sponsor portal/company endpoints
  apps/dashboard/pages/api/companies.ts
  apps/dashboard/pages/api/company/[companyId].ts
  apps/dashboard/repository/company.repository.ts
  apps/dashboard/repository/dashboard.repository.ts
  supabase/migrations/20230125064704_add_notes_and_edit_participants.sql
Labels: automerge

#381 Identity portal
  apps/dashboard/common/add-event-user-id.ts
  apps/dashboard/common/add-event.ts
  apps/dashboard/common/calculate-battlepass-progress.ts
  apps/dashboard/common/format-timestamp.ts
  apps/dashboard/common/search-event-id.ts
  apps/dashboard/common/search-event.ts
  apps/dashboard/common/search-user.ts
  apps/dashboard/components/identity-portal/back-button/back-button.tsx
  apps/dashboard/components/identity-portal/check-in-box/check-in-box.tsx
  apps/dashboard/components/identity-portal/identity-portal.tsx
  apps/dashboard/components/identity-portal/scrollable-list-box/scrollable-list-box.tsx
  apps/dashboard/components/identity-portal/search-event-box/search-event-box.tsx
  apps/dashboard/components/identity-portal/search-user-box/search-user-box.tsx
  apps/dashboard/components/identity-portal/search-user-event-box/search-user-event-box.tsx
  apps/dashboard/components/portal-menu/portal-menu.tsx
  apps/dashboard/pages/api/get-user-hackform.tsx
  apps/dashboard/pages/identity-portal/attendee-details-scan/index.tsx
  apps/dashboard/pages/identity-portal/attendee-details/index.tsx
  apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx
  apps/dashboard/pages/identity-portal/event-checkin/index.tsx
  apps/dashboard/pages/index.tsx
  libs/hibiscus-supabase-client/src/index.ts
  libs/styles/src/lib/colors.ts
  libs/ui-kit-2023/src/lib/button/button.tsx
  libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx
  libs/ui-kit-2023/src/lib/search/search.tsx
  supabase/migrations/20230116025536_add_wristband_id.sql
  supabase/migrations/20230119182613_add_access_policies.sql
  supabase/migrations/20230131165800_add_volunteer_access_participants.sql
  tools/scripts/create-fake-user.ts
Labels: db-migration

#398 Add filter functionality for only basic 3 filters.
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/repository/attendee.repository.ts
Labels: automerge

#400 sponsor updates
  apps/www-2023/components/sponsors/sponsors.tsx
  apps/www-2023/public/img/logos/arrcus.png
  apps/www-2023/public/img/logos/soylent.png
  apps/www-2023/public/img/logos/stickermule.png
Labels: automerge

#399 Hib 150 get all attendees for a sponsor api
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/repository/attendee.repository.ts
  supabase/migrations/20230130024217_add_table_company_saved_user_profiles.sql
Labels: automerge, db-migration

#402 Hib 150 get all attendees for a sponsor api
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/repository/attendee.repository.ts
Labels: automerge

#401 Fix DoB parsing in ID portal
  apps/dashboard/common/parse-dob.ts
  apps/dashboard/common/search-user.ts
Labels: automerge

#404 Make create user script take in role as arg
  tools/scripts/create-user.ts
Labels: automerge

#407 Hib 157 modify company endpoints in sponsor
  apps/dashboard/pages/api/companies/[userId].ts
  apps/dashboard/pages/api/company/[companyId].ts
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/repository/attendee.repository.ts
  apps/dashboard/repository/company.repository.ts
  apps/dashboard/repository/user.repository.ts
  supabase/migrations/20230203200634_bridge_user_profiles_to_company_id.sql
Labels: automerge, db-migration

#408 Implement sponsor portal backend
  apps/dashboard/common/api.ts
  apps/dashboard/common/mock-sponsor.ts
  apps/dashboard/common/schools.ts
  apps/dashboard/components/sponsor-portal/dropdown.tsx
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/hacker-tab.tsx
  apps/dashboard/components/sponsor-portal/sponsor-portal.tsx
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
  apps/dashboard/pages/api/company/[companyId]/save/[participantId].ts
  apps/dashboard/pages/index.tsx
  apps/dashboard/pages/participant-database/index.tsx
  apps/dashboard/pages/sponsor-booth/index.tsx
  apps/dashboard/public/save-green.svg
  apps/dashboard/repository/attendee.repository.ts
  apps/dashboard/repository/company.repository.ts
Labels: automerge

#409 Add resume integration with participants data.
  apps/dashboard/common/api.ts
  apps/dashboard/common/utils.ts
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
Labels: automerge

#410 Jenny/company config
  apps/dashboard/common/api.ts
  apps/dashboard/common/mock-sponsor.ts
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/sponsor-portal.tsx
  apps/dashboard/pages/UploadImage.tsx
  apps/dashboard/pages/company-config/EditForm.tsx
  apps/dashboard/pages/company-config/dropdown/dropdown.module.css
  apps/dashboard/pages/company-config/dropdown/dropdown.spec.tsx
  apps/dashboard/pages/company-config/dropdown/dropdown.tsx
  apps/dashboard/pages/company-config/index.module.css
  apps/dashboard/pages/company-config/index.tsx
  apps/dashboard/pages/index.tsx
  apps/dashboard/public/dropdown.svg
  apps/dashboard/public/edit.svg
  apps/dashboard/public/googleLog.png
  apps/dashboard/store/menu-slice.ts
Labels: automerge

#411 Vincent/battlepass frontend
  .dockerignore
  apps/battlepass-services/.eslintrc.json
  apps/battlepass-services/Dockerfile
  apps/battlepass-services/jest.config.ts
  apps/battlepass-services/project.json
  apps/battlepass-services/src/app/.gitkeep
  apps/battlepass-services/src/app/index.ts
  apps/battlepass-services/src/assets/.gitkeep
  apps/battlepass-services/src/controller/bonusPoints.controller.ts
  apps/battlepass-services/src/controller/leaderboard.controller.ts
  apps/battlepass-services/src/controller/user.controller.ts
  apps/battlepass-services/src/environments/environment.prod.ts
  apps/battlepass-services/src/environments/environment.ts
  apps/battlepass-services/src/main.ts
  apps/battlepass-services/src/repository/bonusPoints.repository.ts
  apps/battlepass-services/src/repository/leaderboard.repository.ts
  apps/battlepass-services/src/repository/user.repository.ts
  apps/battlepass-services/src/routers/bonusPoints.router.ts
  apps/battlepass-services/src/routers/leaderboard.router.ts
  apps/battlepass-services/src/routers/user.router.ts
  apps/battlepass-services/tsconfig.app.json
  apps/battlepass-services/tsconfig.json
  apps/battlepass-services/tsconfig.spec.json
  apps/dashboard/common/apis/battlepass/battlepass.api.ts
  apps/dashboard/common/apis/battlepass/types.ts
  apps/dashboard/common/calculate-battlepass-progress.ts
  apps/dashboard/common/constants.ts
  apps/dashboard/components/battlepass/battlepass-page.tsx
  apps/dashboard/components/battlepass/battlepass-points-bar.tsx
  apps/dashboard/components/battlepass/battlepass-welcome-header.tsx
  apps/dashboard/components/battlepass/bonus-points/bonus-points-item.tsx
  apps/dashboard/components/battlepass/bonus-points/bonus-points-list.tsx
  apps/dashboard/components/battlepass/bonus-points/types.ts
  apps/dashboard/components/battlepass/leaderboard/battlepass-leaderboard.tsx
  apps/dashboard/components/battlepass/leaderboard/types.ts
  apps/dashboard/components/hacker-portal/hacker-portal.tsx
  apps/dashboard/hooks/use-battlepass-api/use-battlepass-api.tsx
  apps/dashboard/next.config.js
  apps/dashboard/pages/index.tsx
  apps/dashboard/repository/battlepass.repository.ts
  apps/dashboard/store/menu-slice.ts
  apps/dashboard/tsconfig.json
  libs/env/src/index.ts
  libs/sso-client/src/lib/sso-client.ts
  libs/types/src/lib/form.ts
  libs/types/src/lib/user.ts
  libs/ui/src/lib/heading/heading.tsx
  package.json
  supabase/migrations/20230126033433_leaderboard_schema_migration.sql
  supabase/migrations/20230204070815_battlepass-redos.sql
  tools/scripts/create-bonus-points.ts
  tools/scripts/create-many-fake-users.ts
  tools/scripts/create-user.ts
  workspace.json
  yarn.lock
Labels: automerge, db-migration

#413 fix sponsor portal
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/components/sponsor-portal/sponsor-portal.tsx
Labels: automerge

#414 fix migration
  supabase/migrations/20230126033433_leaderboard_schema_migration.sql
  supabase/migrations/20230204070815_battlepass-redos.sql
Labels: automerge

#415 patch resume
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
Labels: automerge

#417 Hotfix migrations
  supabase/migrations/20230204070815_battlepass-redos.sql
Labels: automerge, db-migration

#418 Hot fixed resume support.
  apps/dashboard/common/utils.ts
  apps/dashboard/components/sponsor-portal/hacker-profile.tsx
  apps/dashboard/pages/api/company/[companyId]/[eventId].ts
Labels: automerge

#420 Fix excessive API calls
  apps/dashboard/common/parse-dob.ts
  apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx
  apps/dashboard/pages/index.tsx
Labels: automerge

#422 Uncomment feature flags + MongoClient overflow connection fixes
  apps/dashboard/pages/index.tsx
  apps/dashboard/repository/feature-flag.repository.ts
  apps/dashboard/repository/mongo.client.ts
Labels: automerge

#419 updated battlepass ui
  apps/dashboard/components/battlepass/battlepass-page.tsx
Labels: automerge

#430 add central changelog
  CHANGELOG.md
Labels: automerge
